### ISSUE TITLE
Error: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by sulliwane** [reindexio/graphql-nodejs-newsfeed#4] opened 2015-09-14 07:32 UTC
Hello,

thank you for your code. I'm trying to run it, but impossible to properly query the graphql server.

Here is the error I get:

```
#babel-node query.js 
{ data: { viewer: null },
errors: [ { [Error: Cannot read property 'get' of undefined] message: 'Cannot read property \'get\' of undefined' } ] }
```

and here is query.js file:

``` javascript
import {graphql} from 'graphql';
import Schema from './Schema';
import sqlite3 from 'sqlite3';
import {promisify} from 'bluebird';

const db = new sqlite3.Database('db.sqlite3');

db.get = promisify(db.get);
db.all = promisify(db.all);

graphql(Schema, `{
  viewer {
    id,
    name
  }
}`, {db}).then((result) => console.log(result));
```

Any idea about which mistake I'm doing? If you can have a look, it would be very nice of you.

**Comment by freiksenet** [comment] 2015-09-14 07:40
The problem is that the arguments of the resolve have changed in graphql-js. Sorry I had no time to update it. You should change resolve functions third argument, like this:

``` js
resolve(parent, args, { rootValue: { db } })
```

I'll try to update the example asap.

**Comment by sulliwane** [comment] 2015-09-14 08:51
that was fast! it's solved, thankssss.

btw, do you know how to query the graphql server through a browser? I tried with chrome Rest addon but can't get further than this error:

``` javascript
{
statusCode: 400
error: "Bad Request"
message: "Invalid request payload JSON format"
}
```

with this in the POST request:

``` javascript
{
  story(id: "1") {
    id,
    text,
    author {
      id,
      name
    }
  }
}
```

Which work when ran in the console with node (even though it gives me an [OBJECT] at some point):

``` javascript
#babel-node query.js 
{ data: { user: { id: '4', name: 'Sophia', stories: [Object] } } }
```

thanks again !

**Comment by freiksenet** [comment] 2015-09-14 09:05
You need to pass query as part of JSON object.

``` json
{ "query": "your-query-here-as-string"}
```

Eg

``` json
{"query": "{ viewer { name, stories { id } }}"}
```

Remember to escape your quotes:

``` json
{"query": "{ user(id: \"1\") { name, stories { id } }}"}
```

I know it's pretty uncomfortable. You can try https://github.com/graphql/graphiql, it's an "IDE" for graphql. I'll try to add it to this repository at some point, for ease of use.

I've fixed `resolve` functions in the code.

**Comment by freiksenet** [comment] 2015-09-14 09:07
I'll close the issue, but feel free to ask more questions here. There is also graphql slack, where I frequent, you can ask there.

https://graphql-slack.herokuapp.com/

**Closed as completed by freiksenet** 2015-09-14 09:07 UTC

**Comment by sulliwane** [comment] 2015-09-14 09:20
It finally worked, thanks to your help. I will join the slack discussion :)
